<?php

use App\Cliente;
use App\Contato;
use App\Etapa;
use App\Locatario;
use App\Obra;
use App\Subetapa;
use Faker\Factory as Faker;
use Illuminate\Database\Seeder;

class Steel4webTablesSeeder extends Seeder {
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run() {
		if (env('DB_CONNECTION') == 'mysql') {
			DB::statement('SET FOREIGN_KEY_CHECKS=0;');
		}

		if (env('DB_CONNECTION') == 'mysql') {
			DB::table(config('access.assigned_roles_table'))->truncate();
		} elseif (env('DB_CONNECTION') == 'sqlite') {
			DB::statement('DELETE FROM ' . config('access.assigned_roles_table'));
		} else {
			//For PostgreSQL or anything else
			DB::statement('TRUNCATE TABLE ' . config('access.assigned_roles_table') . ' CASCADE');
		}

		$faker = Faker::create('pt_BR');
		$faker->addProvider(new \Faker\Provider\pt_BR\Person($faker));
		$faker->addProvider(new \Faker\Provider\pt_BR\Address($faker));
		// $faker->addProvider(new \Faker\Provider\en_US\Address($faker));
		$faker->addProvider(new \Faker\Provider\en_US\PhoneNumber($faker));
		$faker->addProvider(new \Faker\Provider\pt_BR\Company($faker));
		$faker->addProvider(new \Faker\Provider\Lorem($faker));
		$faker->addProvider(new \Faker\Provider\Internet($faker));

		/* LOCATARIO */
		$locatario_data = [
			'razao' => $faker->firstName() . " " . $faker->lastName(),
			'fantasia' => $faker->company(),
			'tipo' => false,
			'documento' => NULL,
			'inscricao' => NULL,
			'fone' => $faker->phoneNumber(),
			'cidade' => $faker->city(),
			'endereco' => $faker->address(),
			'cep' => '95320-000',
			'email' => $faker->email(),
			'status' => false,
		];

		// DB::table('locatarios')->insert($locatarios);
		$locatario = Locatario::create($locatario_data);

		//Attach first user to locatario
		$user_model = config('auth.providers.users.model');
		$user_model = new $user_model;
		$user_model::first()->locatario_id = $locatario->id;

		echo "Locatario '" . $locatario->fantasia . "' criado com sucesso!\n";

		// CLIENTE
		$cliente_data = [
			'razao' => $faker->company(),
			'fantasia' => $faker->company(),
			'documento' => NULL,
			'inscricao' => NULL,
			'fone' => $faker->phoneNumber(),
			'endereco' => $faker->address(),
			'cep' => '95320-000',
			'responsavel' => $faker->firstName() . " " . $faker->lastName(),
			'email' => $faker->email(),
			'site' => '',
			'user_id' => $user_model::first()->id,
			'locatario_id' => $locatario->id,
		];
		$cliente = Cliente::create($cliente_data);

		echo "Cliente  '" . $cliente->fantasia . "'' criado com sucesso!\n";

		$obra_data = [
			'codigo' => $faker->phoneNumber(),
			'nome' => 'Obra teste',
			'descricao' => 'Descritivo da obra Teste',
			'cidade' => 'New York',
			'endereco' => $faker->address(),
			'cep' => '95320-000',
			'cliente_id' => $cliente->id,
			'gerenciadoraid' => NULL,
			'calculistaid' => NULL,
			'detalhamentoid' => NULL,
			'montagemid' => NULL,
			'status' => true,
			'user_id' => $user_model::first()->id,
			'locatario_id' => $locatario->id,
		];

		$obra = Obra::create($obra_data);

		echo "Obra  '" . $obra->nome . "' criada com sucesso!\n";

		$contato_data = [
			'razao' => $faker->company(),
			'fantasia' => $faker->company(),
			'tipo_id' => NULL,
			'documento' => NULL,
			'inscricao' => NULL,
			'fone' => $faker->phoneNumber(),
			'cidade' => $faker->city(),
			'endereco' => $faker->address(),
			'cep' => '95320-000',
			'responsavel' => NULL,
			'email' => $faker->email(),
			'site' => NULL,
			'cliente_id' => $cliente->id,
			'user_id' => $user_model::first()->id,
			'locatario_id' => $locatario->id,
		];
		$contato = Contato::create($contato_data);
		$contato->obras()->attach($obra->id);
		echo "Contato  '" . $contato->fantasia . "'' vinculado a obra '" . $obra->nome . "'' com sucesso!\n";

		$contato_data = [
			'razao' => $faker->company(),
			'fantasia' => $faker->company(),
			'tipo_id' => NULL,
			'documento' => NULL,
			'inscricao' => NULL,
			'fone' => $faker->phoneNumber(),
			'cidade' => $faker->city(),
			'endereco' => $faker->address(),
			'cep' => '95320-000',
			'responsavel' => NULL,
			'email' => $faker->email(),
			'site' => NULL,
			'cliente_id' => $cliente->id,
			'user_id' => $user_model::first()->id,
			'locatario_id' => $locatario->id,
		];
		$contato = Contato::create($contato_data);
		$contato->obras()->attach($obra->id);
		echo "Contato  '" . $contato->fantasia . "'' vinculado a obra '" . $obra->nome . "'' com sucesso!\n";

		$etapa_data = [
			'codigo' => $faker->phoneNumber(),
			'peso' => 10234,
			'observacao' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi nulla fuga quod sed, tempora quo cumque! Consectetur optio labore tenetur unde aliquam, harum eligendi delectus voluptatem. Alias voluptate tempore libero.',
			'obra_id' => $obra->id,
			'user_id' => $user_model::first()->id,
			'locatario_id' => $locatario->id,
		];

		$etapa = Etapa::create($etapa_data);

		echo "Etapa  " . $etapa->nome . " criada com sucesso!\n";

		// SUBETAPAS
		$subetapas = array(
			array(
				'cod' => 'SUB-001',
				'peso' => '5500',
				'tiposubetapa_id' => NULL,
				'observacao' => 'Nada',
				'etapa_id' => $etapa->id,
				'user_id' => $user_model::first()->id,
				'locatario_id' => $locatario->id,
			),
			array(
				'cod' => 'SUB-002',
				'peso' => '6500',
				'tiposubetapa_id' => NULL,
				'observacao' => 'Teste de observação!',
				'etapa_id' => $etapa->id,
				'user_id' => $user_model::first()->id,
				'locatario_id' => $locatario->id,
			),
		);

		Subetapa::insert($subetapas);
		echo "2 Subbetapas adicionadas com sucesso!\n";

		//
		//   DB::table('cjtofabr')->insert(array(

		//     array(
		//         'id' => 1,
		//         'lote_id' => 1,
		//         'handle_id' => 3,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 3,
		//         'lote_id' => 1,
		//         'handle_id' => 5,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		// ));
		// DB::table('cjtomontagem')->insert(array(

		//     array(
		//         'id' => 1,
		//         'lote_id' => 1,
		//         'obra_id' => 1,
		//         'etapa_id' => 1,
		//         'medicao_id' => 1,
		//         'dataprev_montagem' => '2016-02-06',
		//         'datareal_montagem' => NULL,
		//         'dataprev_entrega' => '2016-02-08',
		//         'datareal_entrega' => NULL,
		//         'montagem' => NULL,
		//         'entrega' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     )

		// ));

		// DB::table('cronos')->insert(array(

		//     array(
		//         'id' => 1,
		//         'estagio_id' => 1,
		//         'cjtofab_id' => 1,
		//         'data_prev' => '2016-01-25',
		//         'data_real' => '2016-01-27',
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 3,
		//         'estagio_id' => 3,
		//         'cjtofab_id' => 1,
		//         'data_prev' => '2016-01-27',
		//         'data_real' => '2016-01-28',
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 5,
		//         'estagio_id' => 5,
		//         'cjtofab_id' => 1,
		//         'data_prev' => '2016-01-29',
		//         'data_real' => '2016-01-30',
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 7,
		//         'estagio_id' => 7,
		//         'cjtofab_id' => 1,
		//         'data_prev' => '2016-01-31',
		//         'data_real' => '2016-01-31',
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 9,
		//         'estagio_id' => 9,
		//         'cjtofab_id' => 1,
		//         'data_prev' => '2016-02-02',
		//         'data_real' => '2016-02-01',
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 11,
		//         'estagio_id' => 11,
		//         'cjtofab_id' => 1,
		//         'data_prev' => '2016-02-04',
		//         'data_real' => '2016-02-05',
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 13,
		//         'estagio_id' => 13,
		//         'cjtofab_id' => 1,
		//         'data_prev' => '2016-02-06',
		//         'data_real' => '0000-00-00',
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 15,
		//         'estagio_id' => 15,
		//         'cjtofab_id' => 1,
		//         'data_prev' => '2016-02-08',
		//         'data_real' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 17,
		//         'estagio_id' => 1,
		//         'cjtofab_id' => 3,
		//         'data_prev' => '2016-01-25',
		//         'data_real' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 19,
		//         'estagio_id' => 3,
		//         'cjtofab_id' => 3,
		//         'data_prev' => '2016-01-27',
		//         'data_real' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 21,
		//         'estagio_id' => 5,
		//         'cjtofab_id' => 3,
		//         'data_prev' => '2016-01-29',
		//         'data_real' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 23,
		//         'estagio_id' => 7,
		//         'cjtofab_id' => 3,
		//         'data_prev' => '2016-01-31',
		//         'data_real' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 25,
		//         'estagio_id' => 9,
		//         'cjtofab_id' => 3,
		//         'data_prev' => '2016-02-02',
		//         'data_real' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 27,
		//         'estagio_id' => 11,
		//         'cjtofab_id' => 3,
		//         'data_prev' => '2016-02-04',
		//         'data_real' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 29,
		//         'estagio_id' => 13,
		//         'cjtofab_id' => 3,
		//         'data_prev' => '2016-02-06',
		//         'data_real' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 31,
		//         'estagio_id' => 15,
		//         'cjtofab_id' => 3,
		//         'data_prev' => '2016-02-08',
		//         'data_real' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		// ));
		// DB::table('estagios')->insert(array(

		//     array(
		//         'id' => 1,
		//         'decricao' => 'PCP',
		//         'ordem' => 1,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 3,
		//         'decricao' => 'Preparacao',
		//         'ordem' => 2,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 5,
		//         'decricao' => 'Gabarito',
		//         'ordem' => 3,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 7,
		//         'decricao' => 'Solda',
		//         'ordem' => 4,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 9,
		//         'decricao' => 'Pintura',
		//         'ordem' => 5,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 11,
		//         'decricao' => 'Expedicao',
		//         'ordem' => 6,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 13,
		//         'decricao' => 'Montagem',
		//         'ordem' => 7,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 15,
		//         'decricao' => 'Entrega Final',
		//         'ordem' => 8,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		// ));
		// DB::table('etapas')->insert(array(

		//     array(
		//         'id' => 1,
		//         'codigo' => 1,
		//         'peso' => 1,
		//         'obra_id' => 1,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     )

		// ));
		// DB::table('handles')->insert(array(

		//     array(
		//         'id' => 3,
		//         'HANDLE' => 'D5',
		//         'FLG_REC' => 3,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M1',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'W150X18.00',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => '1013 X 699 X 142',
		//         'MAX_LEN' => 1000,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => 'W150X18.00',
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 'FE360B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 0,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 13,
		//         'etapa_id' => 1,
		//         'GROUP' => 'AC48235D749847C7BF615264383C9C8B',
		//         'CATE' => 3,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>       0.000,
		//         'Y' =>    -582.000,
		//         'Z' =>       0.000,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 5,
		//         'HANDLE' => 110,
		//         'FLG_REC' => 3,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M1',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'W150X18.00',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => '1013 X 699 X 142',
		//         'MAX_LEN' => 1000,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => 'W150X18.00',
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 'FE360B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 0,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'DF510C42AC684D4CAA150D0535643495',
		//         'CATE' => 3,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>    1500.000,
		//         'Y' =>    -582.000,
		//         'Z' =>       0.000,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 7,
		//         'HANDLE' => '11A',
		//         'FLG_REC' => 3,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M2',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'W150X13.0',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => '1494 X 148 X 120',
		//         'MAX_LEN' => 1468,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => 'W150X13.0',
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 'FE360B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 0,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'A7AA2713227F478F9E94677FE59D2CFA',
		//         'CATE' => 3,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>      15.900,
		//         'Y' =>    -505.700,
		//         'Z' =>     999.500,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 9,
		//         'HANDLE' => 'CF',
		//         'FLG_REC' => 3,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M2',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'W150X13.0',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => '1494 X 148 X 120',
		//         'MAX_LEN' => 1468,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => 'W150X13.0',
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 'FE360B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 0,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'FBE84455638840B2BD4EEF1005D9AEAF',
		//         'CATE' => 3,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>      15.900,
		//         'Y' =>       0.300,
		//         'Z' =>     999.500,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 11,
		//         'HANDLE' => 'D5',
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M1',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P1',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => 'W150X18.00',
		//         'LUN_PRO' => 999.64,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 'FE360B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 18.34,
		//         'SUN_LIS' => 0.69,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'AC48235D749847C7BF615264383C9C8B',
		//         'CATE' => 3,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>       0.000,
		//         'Y' =>    -582.000,
		//         'Z' =>       0.000,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 13,
		//         'HANDLE' => 'D4',
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M1',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P1',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => 'W150X18.00',
		//         'LUN_PRO' => 999.64,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 'FE360B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 18.34,
		//         'SUN_LIS' => 0.69,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'AC48235D749847C7BF615264383C9C8B',
		//         'CATE' => 3,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>       0.000,
		//         'Y' =>     -76.000,
		//         'Z' =>       0.000,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 15,
		//         'HANDLE' => 110,
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M1',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P1',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => 'W150X18.00',
		//         'LUN_PRO' => 999.64,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 'FE360B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 18.34,
		//         'SUN_LIS' => 0.69,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'DF510C42AC684D4CAA150D0535643495',
		//         'CATE' => 3,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>    1500.000,
		//         'Y' =>    -582.000,
		//         'Z' =>       0.000,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 17,
		//         'HANDLE' => '10F',
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M1',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P1',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => 'W150X18.00',
		//         'LUN_PRO' => 999.64,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 'FE360B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 18.34,
		//         'SUN_LIS' => 0.69,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'DF510C42AC684D4CAA150D0535643495',
		//         'CATE' => 3,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>    1500.000,
		//         'Y' =>     -76.000,
		//         'Z' =>       0.000,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 19,
		//         'HANDLE' => 'EA',
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M1',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P2',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 193,
		//         'LAR_PRO' => 142,
		//         'SPE_PRO' => 13,
		//         'MAT_PRO' => 'FE430B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 2.8,
		//         'SUN_LIS' => 0.06,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'AC48235D749847C7BF615264383C9C8B',
		//         'CATE' => 0,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>       0.000,
		//         'Y' =>    -506.000,
		//         'Z' =>     -13.000,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 21,
		//         'HANDLE' => 'DC',
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M1',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P2',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 193,
		//         'LAR_PRO' => 142,
		//         'SPE_PRO' => 13,
		//         'MAT_PRO' => 'FE430B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 2.8,
		//         'SUN_LIS' => 0.06,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'AC48235D749847C7BF615264383C9C8B',
		//         'CATE' => 0,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>       0.000,
		//         'Y' =>       0.000,
		//         'Z' =>     -13.000,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 23,
		//         'HANDLE' => 113,
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M1',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P2',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 193,
		//         'LAR_PRO' => 142,
		//         'SPE_PRO' => 13,
		//         'MAT_PRO' => 'FE430B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 2.8,
		//         'SUN_LIS' => 0.06,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'DF510C42AC684D4CAA150D0535643495',
		//         'CATE' => 0,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>    1500.000,
		//         'Y' =>    -506.000,
		//         'Z' =>     -13.000,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 25,
		//         'HANDLE' => 112,
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M1',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P2',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 193,
		//         'LAR_PRO' => 142,
		//         'SPE_PRO' => 13,
		//         'MAT_PRO' => 'FE430B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 2.8,
		//         'SUN_LIS' => 0.06,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'DF510C42AC684D4CAA150D0535643495',
		//         'CATE' => 0,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>    1500.000,
		//         'Y' =>       0.000,
		//         'Z' =>     -13.000,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 27,
		//         'HANDLE' => 'D6',
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M1',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P3',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => 'W150X18.00',
		//         'LUN_PRO' => 352.37,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 'FE360B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 6.48,
		//         'SUN_LIS' => 0.24,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'AC48235D749847C7BF615264383C9C8B',
		//         'CATE' => 3,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>       0.400,
		//         'Y' =>     -76.400,
		//         'Z' =>     846.600,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 29,
		//         'HANDLE' => 111,
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M1',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P3',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => 'W150X18.00',
		//         'LUN_PRO' => 352.37,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 'FE360B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 6.48,
		//         'SUN_LIS' => 0.24,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'DF510C42AC684D4CAA150D0535643495',
		//         'CATE' => 3,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>    1500.400,
		//         'Y' =>     -76.400,
		//         'Z' =>     846.600,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 31,
		//         'HANDLE' => '11A',
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M2',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P4',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => 'W150X13.0',
		//         'LUN_PRO' => 1468.2,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 'FE360B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 19.16,
		//         'SUN_LIS' => 0.98,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'A7AA2713227F478F9E94677FE59D2CFA',
		//         'CATE' => 3,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>      15.900,
		//         'Y' =>    -505.700,
		//         'Z' =>     999.500,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 33,
		//         'HANDLE' => 'CF',
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M2',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P4',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => 'W150X13.0',
		//         'LUN_PRO' => 1468.2,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 'FE360B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 19.16,
		//         'SUN_LIS' => 0.98,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'FBE84455638840B2BD4EEF1005D9AEAF',
		//         'CATE' => 3,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>      15.900,
		//         'Y' =>       0.300,
		//         'Z' =>     999.500,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 35,
		//         'HANDLE' => '11C',
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M2',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P5',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 120,
		//         'LAR_PRO' => 130,
		//         'SPE_PRO' => 13,
		//         'MAT_PRO' => 'FE430B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 1.53,
		//         'SUN_LIS' => 0.04,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'A7AA2713227F478F9E94677FE59D2CFA',
		//         'CATE' => 0,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>    1497.100,
		//         'Y' =>    -505.700,
		//         'Z' =>     999.500,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 37,
		//         'HANDLE' => '11B',
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M2',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P5',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 120,
		//         'LAR_PRO' => 130,
		//         'SPE_PRO' => 13,
		//         'MAT_PRO' => 'FE430B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 1.53,
		//         'SUN_LIS' => 0.04,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'A7AA2713227F478F9E94677FE59D2CFA',
		//         'CATE' => 0,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>       2.900,
		//         'Y' =>    -505.700,
		//         'Z' =>     999.500,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 39,
		//         'HANDLE' => 115,
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M2',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P5',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 120,
		//         'LAR_PRO' => 130,
		//         'SPE_PRO' => 13,
		//         'MAT_PRO' => 'FE430B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 1.53,
		//         'SUN_LIS' => 0.04,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'FBE84455638840B2BD4EEF1005D9AEAF',
		//         'CATE' => 0,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>    1497.100,
		//         'Y' =>       0.300,
		//         'Z' =>     999.500,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 41,
		//         'HANDLE' => 'F4',
		//         'FLG_REC' => 4,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => NULL,
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => 'M2',
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => NULL,
		//         'POS_PEZ' => 'P5',
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 120,
		//         'LAR_PRO' => 130,
		//         'SPE_PRO' => 13,
		//         'MAT_PRO' => 'FE430B',
		//         'TIP_BUL' => NULL,
		//         'DIA_BUL' => NULL,
		//         'LUN_BUL' => NULL,
		//         'PRB_BUL' => NULL,
		//         'PUN_LIS' => 1.53,
		//         'SUN_LIS' => 0.04,
		//         'PRE_LIS' => 'Ch.',
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => 'FBE84455638840B2BD4EEF1005D9AEAF',
		//         'CATE' => 0,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>       2.900,
		//         'Y' =>       0.300,
		//         'Z' =>     999.500,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 43,
		//         'HANDLE' => 119,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' =>    1502.900,
		//         'Y' =>      35.300,
		//         'Z' =>     949.500,
		//         'A' =>          0,
		//         'B' =>          0,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 45,
		//         'HANDLE' => NULL,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' => NULL,
		//         'Y' => NULL,
		//         'Z' => NULL,
		//         'A' => NULL,
		//         'B' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 47,
		//         'HANDLE' => NULL,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' => NULL,
		//         'Y' => NULL,
		//         'Z' => NULL,
		//         'A' => NULL,
		//         'B' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 49,
		//         'HANDLE' => NULL,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' => NULL,
		//         'Y' => NULL,
		//         'Z' => NULL,
		//         'A' => NULL,
		//         'B' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 51,
		//         'HANDLE' => NULL,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' => NULL,
		//         'Y' => NULL,
		//         'Z' => NULL,
		//         'A' => NULL,
		//         'B' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 53,
		//         'HANDLE' => NULL,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' => NULL,
		//         'Y' => NULL,
		//         'Z' => NULL,
		//         'A' => NULL,
		//         'B' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 55,
		//         'HANDLE' => NULL,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' => NULL,
		//         'Y' => NULL,
		//         'Z' => NULL,
		//         'A' => NULL,
		//         'B' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 57,
		//         'HANDLE' => NULL,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' => NULL,
		//         'Y' => NULL,
		//         'Z' => NULL,
		//         'A' => NULL,
		//         'B' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 59,
		//         'HANDLE' => NULL,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' => NULL,
		//         'Y' => NULL,
		//         'Z' => NULL,
		//         'A' => NULL,
		//         'B' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 61,
		//         'HANDLE' => NULL,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' => NULL,
		//         'Y' => NULL,
		//         'Z' => NULL,
		//         'A' => NULL,
		//         'B' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 63,
		//         'HANDLE' => NULL,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' => NULL,
		//         'Y' => NULL,
		//         'Z' => NULL,
		//         'A' => NULL,
		//         'B' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 65,
		//         'HANDLE' => NULL,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' => NULL,
		//         'Y' => NULL,
		//         'Z' => NULL,
		//         'A' => NULL,
		//         'B' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 67,
		//         'HANDLE' => NULL,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' => NULL,
		//         'Y' => NULL,
		//         'Z' => NULL,
		//         'A' => NULL,
		//         'B' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 69,
		//         'HANDLE' => NULL,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' => NULL,
		//         'Y' => NULL,
		//         'Z' => NULL,
		//         'A' => NULL,
		//         'B' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 71,
		//         'HANDLE' => NULL,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' => NULL,
		//         'Y' => NULL,
		//         'Z' => NULL,
		//         'A' => NULL,
		//         'B' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		//     array(
		//         'id' => 73,
		//         'HANDLE' => NULL,
		//         'FLG_REC' => 6,
		//         'NUM_COM' => 'MESA',
		//         'DES_COM' => NULL,
		//         'LOT_COM' => NULL,
		//         'DLO_COM' => NULL,
		//         'CLI_COM' => NULL,
		//         'IND_COM' => NULL,
		//         'DT1_COM' => '05/01/16',
		//         'DT2_COM' => NULL,
		//         'NUM_DIS' => 'D101',
		//         'DES_DIS' => NULL,
		//         'NOM_DIS' => NULL,
		//         'REV_DIS' => NULL,
		//         'DAT_DIS' => '05/01/16',
		//         'TRA_PEZ' => 'PINTADO',
		//         'SBA_PEZ' => NULL,
		//         'DES_SBA' => NULL,
		//         'TIP_PEZ' => NULL,
		//         'MAR_PEZ' => NULL,
		//         'MBU_PEZ' => NULL,
		//         'DES_PEZ' => 'A325 A325',
		//         'POS_PEZ' => NULL,
		//         'NOT_PEZ' => NULL,
		//         'ING_PEZ' => NULL,
		//         'MAX_LEN' => NULL,
		//         'QTA_PEZ' => 1,
		//         'QT1_PEZ' => NULL,
		//         'MCL_PEZ' => NULL,
		//         'COD_PEZ' => NULL,
		//         'COS_PEZ' => NULL,
		//         'NOM_PRO' => NULL,
		//         'LUN_PRO' => 0,
		//         'LAR_PRO' => 0,
		//         'SPE_PRO' => 0,
		//         'MAT_PRO' => 0502,
		//         'TIP_BUL' => 'A',
		//         'DIA_BUL' => 12.00,
		//         'LUN_BUL' =>  44.40,
		//         'PRB_BUL' => 'Prf',
		//         'PUN_LIS' => 0.11,
		//         'SUN_LIS' => 0,
		//         'PRE_LIS' => NULL,
		//         'FLG_DWG' => 'D101',
		//         'obra_id' => 1,
		//         'lote_id' => 1,
		//         'estagio_id' => 1,
		//         'etapa_id' => 1,
		//         'GROUP' => NULL,
		//         'CATE' => NULL,
		//         'importacao_id' => 7,
		//         'medicao_id' => 1,
		//         'X' => NULL,
		//         'Y' => NULL,
		//         'Z' => NULL,
		//         'A' => NULL,
		//         'B' => NULL,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     ),

		// ));
		// DB::table('importacoes')->insert(array(

		//     array(
		//         'id' => 7,
		//         'description' => 'mesa-software.DBF',
		//         'cliente_id' => 1,
		//         'obra_id' => 1,
		//         'etapa_id' => 1,
		//         'subetapa_id' => 1,
		//         'dbf2d' => 'mesa-software.DBF',
		//         'ifc' => '1_ifc.obj',
		//         'fbx' => '1_fbx.obj',
		//         'ifc_orig' => 'mesa.ifc',
		//         'fbx_orig' => 'MESA.fbx',
		//         'erro_debug' => 'mesa-software.DBF',
		//         'importacaoNr' => 1,
		//         'observacoes' => NULL,
		//         'sentido' => 1,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     )

		// ));
		// DB::table('locatarios')->insert(array(

		//     array(
		//         'id' => 1,
		//         'razao' => 1,
		//         'fantasia' => 1,
		//         'tipo' => 1,
		//         'documento' => 1,
		//         'inscricao' => 1,
		//         'fone' => 1,
		//         'cidade' => 1,
		//         'endereco' => 1,
		//         'cep' => 1,
		//         'email' => 1,
		//         'status' => 1,
		//         'data' => '2016-01-24 21:21:35',
		//     )

		// ));
		// DB::table('lotes')->insert(array(

		//     array(
		//         'id' => 1,
		//         'descricao' => 'Lote dos CJ1',
		//         'obra_id' => 1,
		//         'etapa_id' => 1,
		//         'subetapa_id' => 1,
		//         'producao' => 1,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     )

		// ));
		// DB::table('medicoes')->insert(array(

		//     array(
		//         'id' => 1,
		//         'descricao' => 1,
		//         'periodo' => 1,
		//         'montador' => 1,
		//         'obs' => 1,
		//         'etapa_id' => 1,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     )

		// ));
		// DB::table('obras')->insert(array(

		//     array(
		//         'id' => 1,
		//         'codigo' => 1,
		//         'nome' => 1,
		//         'descricao' => 1,
		//         'cidade' => 1,
		//         'endereco' => 1,
		//         'cep' => 1,
		//         'cliente_id' => 1,
		//         'construtoraid' => 1,
		//         'gerenciadoraid' => NULL,
		//         'calculistaid' => 1,
		//         'detalhamentoid' => 1,
		//         'montagemid' => 1,
		//         'data' => '2016-01-24 21:22:34',
		//         'status' => 1,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     )

		// ));
		// DB::table('roles')->insert(array(

		//     array(
		//         'id' => 1,
		//         'name' => 'Administrator',
		//         'all' => 1,
		//         'sort' => 1,
		//         'created_at' => '2016-01-24 01:31:55',
		//         'updated_at' => '2016-01-24 01:31:55',
		//     ),

		//     array(
		//         'id' => 3,
		//         'name' => 'User',
		//         'all' => 0,
		//         'sort' => 2,
		//         'created_at' => '2016-01-24 01:31:55',
		//         'updated_at' => '2016-01-24 01:31:55',
		//     ),

		// ));
		// DB::table('subetapas')->insert(array(

		//     array(
		//         'id' => 1,
		//         'cod' => 1,
		//         'peso' => 1,
		//         'tiposubetapa_id' => 1,
		//         'observacao' => 1,
		//         'etapa_id' => 1,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//         'created_at' => '0000-00-00 00:00:00',
		//         'updated_at' => '0000-00-00 00:00:00',
		//     )

		// ));
		// DB::table('tipossubetapas')->insert(array(

		//     array(
		//         'id' => 1,
		//         'descricao' => 1,
		//         'user_id' => 1,
		//         'locatario_id' => 1,
		//     )

		// ));

		if (env('DB_CONNECTION') == 'mysql') {
			DB::statement('SET FOREIGN_KEY_CHECKS=1;');
		}
	}
}
