<?php
use Faker\Factory as Faker;
use Illuminate\Database\Seeder;

class steel4webTableSeeder extends Seeder {
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run() {
		if (env('DB_CONNECTION') == 'mysql') {
			DB::statement('SET FOREIGN_KEY_CHECKS=0;');
		}

		if (env('DB_CONNECTION') == 'mysql') {
			DB::table(config('access.assigned_roles_table'))->truncate();
		} elseif (env('DB_CONNECTION') == 'sqlite') {
			DB::statement('DELETE FROM ' . config('access.assigned_roles_table'));
		} else {
			//For PostgreSQL or anything else
			DB::statement('TRUNCATE TABLE ' . config('access.assigned_roles_table') . ' CASCADE');
		}

		$faker = Faker::create('pt_BR');
		$faker->addProvider(new \Faker\Provider\pt_BR\Person($faker));
		$faker->addProvider(new \Faker\Provider\pt_BR\Address($faker));
		// $faker->addProvider(new \Faker\Provider\en_US\Address($faker));
		$faker->addProvider(new \Faker\Provider\en_US\PhoneNumber($faker));
		$faker->addProvider(new \Faker\Provider\pt_BR\Company($faker));
		$faker->addProvider(new \Faker\Provider\Lorem($faker));
		$faker->addProvider(new \Faker\Provider\Internet($faker));

		DB::table('assigned_roles')->insert(array(

			array(
				'id' => 1,
				'user_id' => 1,
				'role_id' => 1,
			),

			array(
				'id' => 3,
				'user_id' => 2,
				'role_id' => 1,
			),

			array(
				'id' => 5,
				'user_id' => 5,
				'role_id' => 1,
			),

		));
		DB::table('clientes')->insert(array(

			array(
				'id' => 1,
				'tipo' => NULL,
				'razao' => 'TransVilmar',
				'fantasia' => 'TransVilmar',
				'documento' => NULL,
				'inscricao' => NULL,
				'fone' => NULL,
				'endereco' => NULL,
				'cep' => NULL,
				'responsavel' => NULL,
				'email' => NULL,
				'site' => NULL,
				'user_id' => 1,
				'locatario_id' => 1,
				'created_at' => '2016-01-25 20:47:10',
				'updated_at' => '2016-01-25 20:47:10',
			),

		));
		DB::table('contatos')->insert(array(

			array(
				'id' => 1,
				'razao' => 'Lozano, Bittencourt e Fontes',
				'fantasia' => 'Urias de Rezende',
				'tipo_id' => NULL,
				'documento' => NULL,
				'inscricao' => NULL,
				'fone' => '(779)770-7824x0448',
				'cidade' => 'Simão d\'Oeste',
				'endereco' => '39686-489, Largo Marés, 61
Carmona do Leste - SE',
				'cep' => '95320-000',
				'responsavel' => NULL,
				'email' => 'Ziraldo02@Zaragoca.com',
				'site' => NULL,
				'crea' => NULL,
				'cliente_id' => 1,
				'user_id' => 1,
				'locatario_id' => 1,
				'created_at' => '2016-01-25 20:47:10',
				'updated_at' => '2016-01-25 20:47:10',
			),

			array(
				'id' => 2,
				'razao' => 'Zambrano, Leon e das Neves',
				'fantasia' => 'Toledo, Camacho e Rivera',
				'tipo_id' => NULL,
				'documento' => NULL,
				'inscricao' => NULL,
				'fone' => 02724830757,
				'cidade' => 'Santa Emílio',
				'endereco' => '91793-916, Rua Toledo, 83
Adriana do Sul - SE',
				'cep' => '95320-000',
				'responsavel' => NULL,
				'email' => 'Marques.Josefina@yahoo.com',
				'site' => NULL,
				'crea' => NULL,
				'cliente_id' => 1,
				'user_id' => 1,
				'locatario_id' => 1,
				'created_at' => '2016-01-25 20:47:11',
				'updated_at' => '2016-01-25 20:47:11',
			),

		));
		DB::table('estagios')->insert(array(

			array(
				'id' => 1,
				'descricao' => 'PCP',
				'ordem' => 1,
				'tipoestagio_id' => 2,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),

			array(
				'id' => 2,
				'descricao' => 'Preparação',
				'ordem' => 2,
				'tipoestagio_id' => 2,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),

			array(
				'id' => 3,
				'descricao' => 'Gabarito',
				'ordem' => 3,
				'tipoestagio_id' => 2,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),

			array(
				'id' => 4,
				'descricao' => 'Solda',
				'ordem' => 4,
				'tipoestagio_id' => 2,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),

			array(
				'id' => 5,
				'descricao' => 'Pintura',
				'ordem' => 5,
				'tipoestagio_id' => 2,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),

			array(
				'id' => 6,
				'descricao' => 'Expedição',
				'ordem' => 6,
				'tipoestagio_id' => 2,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),

			array(
				'id' => 7,
				'descricao' => 'Montagem',
				'ordem' => 7,
				'tipoestagio_id' => 2,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),

			array(
				'id' => 8,
				'descricao' => 'Entrega Final',
				'ordem' => 8,
				'tipoestagio_id' => 2,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),

		));
		DB::table('etapas')->insert(array(

			array(
				'id' => 11,
				'codigo' => 'Unica-Trans',
				'peso' => NULL,
				'observacao' => NULL,
				'obra_id' => 1,
				'user_id' => 4,
				'locatario_id' => 1,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),

			array(
				'id' => 13,
				'codigo' => 'MESA',
				'peso' => 500,
				'observacao' => 'Mesa',
				'obra_id' => 1,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:29:32',
				'updated_at' => '2016-02-01 11:29:32',
			),

		));
		DB::table('handles')->insert(array(

			array(
				'id' => 3721,
				'HANDLE' => 'D5',
				'FLG_REC' => 3,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M1',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'W150X18.00',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => '1013 X 699 X 142',
				'MAX_LEN' => 1000,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => 'W150X18.00',
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 'FE360B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 0,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => 21,
				'GROUP' => 'AC48235D749847C7BF615264383C9C8B',
				'CATE' => 3,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 0.000,
				'Y' => -582.000,
				'Z' => 0.000,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:04',
				'updated_at' => '2016-02-01 11:32:04',
			),

			array(
				'id' => 3723,
				'HANDLE' => 110,
				'FLG_REC' => 3,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M1',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'W150X18.00',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => '1013 X 699 X 142',
				'MAX_LEN' => 1000,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => 'W150X18.00',
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 'FE360B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 0,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => 21,
				'GROUP' => 'DF510C42AC684D4CAA150D0535643495',
				'CATE' => 3,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 1500.000,
				'Y' => -582.000,
				'Z' => 0.000,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:04',
				'updated_at' => '2016-02-01 11:32:04',
			),

			array(
				'id' => 3725,
				'HANDLE' => '11A',
				'FLG_REC' => 3,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M2',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'W150X13.0',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => '1494 X 148 X 120',
				'MAX_LEN' => 1468,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => 'W150X13.0',
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 'FE360B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 0,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => 21,
				'GROUP' => 'A7AA2713227F478F9E94677FE59D2CFA',
				'CATE' => 3,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 15.900,
				'Y' => -505.700,
				'Z' => 999.500,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:05',
				'updated_at' => '2016-02-01 11:32:05',
			),

			array(
				'id' => 3727,
				'HANDLE' => 'CF',
				'FLG_REC' => 3,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M2',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'W150X13.0',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => '1494 X 148 X 120',
				'MAX_LEN' => 1468,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => 'W150X13.0',
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 'FE360B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 0,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => 21,
				'GROUP' => 'FBE84455638840B2BD4EEF1005D9AEAF',
				'CATE' => 3,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 15.900,
				'Y' => 0.300,
				'Z' => 999.500,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:05',
				'updated_at' => '2016-02-01 11:32:05',
			),

			array(
				'id' => 3729,
				'HANDLE' => 'D5',
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M1',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P1',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => 'W150X18.00',
				'LUN_PRO' => 999.64,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 'FE360B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 18.34,
				'SUN_LIS' => 0.69,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => 'AC48235D749847C7BF615264383C9C8B',
				'CATE' => 3,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 0.000,
				'Y' => -582.000,
				'Z' => 0.000,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:05',
				'updated_at' => '2016-02-01 11:32:05',
			),

			array(
				'id' => 3731,
				'HANDLE' => 'D4',
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M1',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P1',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => 'W150X18.00',
				'LUN_PRO' => 999.64,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 'FE360B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 18.34,
				'SUN_LIS' => 0.69,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => 'AC48235D749847C7BF615264383C9C8B',
				'CATE' => 3,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 0.000,
				'Y' => -76.000,
				'Z' => 0.000,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:05',
				'updated_at' => '2016-02-01 11:32:05',
			),

			array(
				'id' => 3733,
				'HANDLE' => 110,
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M1',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P1',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => 'W150X18.00',
				'LUN_PRO' => 999.64,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 'FE360B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 18.34,
				'SUN_LIS' => 0.69,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => 'DF510C42AC684D4CAA150D0535643495',
				'CATE' => 3,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 1500.000,
				'Y' => -582.000,
				'Z' => 0.000,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:05',
				'updated_at' => '2016-02-01 11:32:05',
			),

			array(
				'id' => 3735,
				'HANDLE' => '10F',
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M1',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P1',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => 'W150X18.00',
				'LUN_PRO' => 999.64,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 'FE360B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 18.34,
				'SUN_LIS' => 0.69,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => 'DF510C42AC684D4CAA150D0535643495',
				'CATE' => 3,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 1500.000,
				'Y' => -76.000,
				'Z' => 0.000,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:05',
				'updated_at' => '2016-02-01 11:32:05',
			),

			array(
				'id' => 3737,
				'HANDLE' => 'EA',
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M1',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P2',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 193,
				'LAR_PRO' => 142,
				'SPE_PRO' => 13,
				'MAT_PRO' => 'FE430B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 2.8,
				'SUN_LIS' => 0.06,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => 'AC48235D749847C7BF615264383C9C8B',
				'CATE' => 0,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 0.000,
				'Y' => -506.000,
				'Z' => -13.000,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:05',
				'updated_at' => '2016-02-01 11:32:05',
			),

			array(
				'id' => 3739,
				'HANDLE' => 'DC',
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M1',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P2',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 193,
				'LAR_PRO' => 142,
				'SPE_PRO' => 13,
				'MAT_PRO' => 'FE430B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 2.8,
				'SUN_LIS' => 0.06,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => 'AC48235D749847C7BF615264383C9C8B',
				'CATE' => 0,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 0.000,
				'Y' => 0.000,
				'Z' => -13.000,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:05',
				'updated_at' => '2016-02-01 11:32:05',
			),

			array(
				'id' => 3741,
				'HANDLE' => 113,
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M1',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P2',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 193,
				'LAR_PRO' => 142,
				'SPE_PRO' => 13,
				'MAT_PRO' => 'FE430B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 2.8,
				'SUN_LIS' => 0.06,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => 'DF510C42AC684D4CAA150D0535643495',
				'CATE' => 0,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 1500.000,
				'Y' => -506.000,
				'Z' => -13.000,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:06',
				'updated_at' => '2016-02-01 11:32:06',
			),

			array(
				'id' => 3743,
				'HANDLE' => 112,
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M1',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P2',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 193,
				'LAR_PRO' => 142,
				'SPE_PRO' => 13,
				'MAT_PRO' => 'FE430B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 2.8,
				'SUN_LIS' => 0.06,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => 21,
				'GROUP' => 'DF510C42AC684D4CAA150D0535643495',
				'CATE' => 0,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 1500.000,
				'Y' => 0.000,
				'Z' => -13.000,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:06',
				'updated_at' => '2016-02-01 11:32:06',
			),

			array(
				'id' => 3745,
				'HANDLE' => 'D6',
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M1',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P3',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => 'W150X18.00',
				'LUN_PRO' => 352.37,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 'FE360B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 6.48,
				'SUN_LIS' => 0.24,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => 21,
				'GROUP' => 'AC48235D749847C7BF615264383C9C8B',
				'CATE' => 3,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 0.400,
				'Y' => -76.400,
				'Z' => 846.600,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:06',
				'updated_at' => '2016-02-01 11:32:06',
			),

			array(
				'id' => 3747,
				'HANDLE' => 111,
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M1',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P3',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => 'W150X18.00',
				'LUN_PRO' => 352.37,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 'FE360B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 6.48,
				'SUN_LIS' => 0.24,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => 21,
				'GROUP' => 'DF510C42AC684D4CAA150D0535643495',
				'CATE' => 3,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 1500.400,
				'Y' => -76.400,
				'Z' => 846.600,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:06',
				'updated_at' => '2016-02-01 11:32:06',
			),

			array(
				'id' => 3749,
				'HANDLE' => '11A',
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M2',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P4',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => 'W150X13.0',
				'LUN_PRO' => 1468.2,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 'FE360B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 19.16,
				'SUN_LIS' => 0.98,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => 21,
				'GROUP' => 'A7AA2713227F478F9E94677FE59D2CFA',
				'CATE' => 3,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 15.900,
				'Y' => -505.700,
				'Z' => 999.500,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:06',
				'updated_at' => '2016-02-01 11:32:06',
			),

			array(
				'id' => 3751,
				'HANDLE' => 'CF',
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M2',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P4',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => 'W150X13.0',
				'LUN_PRO' => 1468.2,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 'FE360B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 19.16,
				'SUN_LIS' => 0.98,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => 21,
				'GROUP' => 'FBE84455638840B2BD4EEF1005D9AEAF',
				'CATE' => 3,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 15.900,
				'Y' => 0.300,
				'Z' => 999.500,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:06',
				'updated_at' => '2016-02-01 11:32:06',
			),

			array(
				'id' => 3753,
				'HANDLE' => '11C',
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M2',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P5',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 120,
				'LAR_PRO' => 130,
				'SPE_PRO' => 13,
				'MAT_PRO' => 'FE430B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 1.53,
				'SUN_LIS' => 0.04,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => 21,
				'GROUP' => 'A7AA2713227F478F9E94677FE59D2CFA',
				'CATE' => 0,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 1497.100,
				'Y' => -505.700,
				'Z' => 999.500,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:06',
				'updated_at' => '2016-02-01 11:32:06',
			),

			array(
				'id' => 3755,
				'HANDLE' => '11B',
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M2',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P5',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 120,
				'LAR_PRO' => 130,
				'SPE_PRO' => 13,
				'MAT_PRO' => 'FE430B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 1.53,
				'SUN_LIS' => 0.04,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => 21,
				'GROUP' => 'A7AA2713227F478F9E94677FE59D2CFA',
				'CATE' => 0,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 2.900,
				'Y' => -505.700,
				'Z' => 999.500,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:06',
				'updated_at' => '2016-02-01 11:32:06',
			),

			array(
				'id' => 3757,
				'HANDLE' => 115,
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M2',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P5',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 120,
				'LAR_PRO' => 130,
				'SPE_PRO' => 13,
				'MAT_PRO' => 'FE430B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 1.53,
				'SUN_LIS' => 0.04,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => 'FBE84455638840B2BD4EEF1005D9AEAF',
				'CATE' => 0,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 1497.100,
				'Y' => 0.300,
				'Z' => 999.500,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:07',
				'updated_at' => '2016-02-01 11:32:07',
			),

			array(
				'id' => 3759,
				'HANDLE' => 'F4',
				'FLG_REC' => 4,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => NULL,
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => 'M2',
				'MBU_PEZ' => NULL,
				'DES_PEZ' => NULL,
				'POS_PEZ' => 'P5',
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 120,
				'LAR_PRO' => 130,
				'SPE_PRO' => 13,
				'MAT_PRO' => 'FE430B',
				'TIP_BUL' => NULL,
				'DIA_BUL' => NULL,
				'LUN_BUL' => NULL,
				'PRB_BUL' => NULL,
				'PUN_LIS' => 1.53,
				'SUN_LIS' => 0.04,
				'PRE_LIS' => 'Ch.',
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => 'FBE84455638840B2BD4EEF1005D9AEAF',
				'CATE' => 0,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 2.900,
				'Y' => 0.300,
				'Z' => 999.500,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:07',
				'updated_at' => '2016-02-01 11:32:07',
			),

			array(
				'id' => 3761,
				'HANDLE' => 119,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => 1502.900,
				'Y' => 35.300,
				'Z' => 949.500,
				'A' => 0,
				'B' => 0,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:07',
				'updated_at' => '2016-02-01 11:32:07',
			),

			array(
				'id' => 3763,
				'HANDLE' => NULL,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => NULL,
				'Y' => NULL,
				'Z' => NULL,
				'A' => NULL,
				'B' => NULL,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:07',
				'updated_at' => '2016-02-01 11:32:07',
			),

			array(
				'id' => 3765,
				'HANDLE' => NULL,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => NULL,
				'Y' => NULL,
				'Z' => NULL,
				'A' => NULL,
				'B' => NULL,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:07',
				'updated_at' => '2016-02-01 11:32:07',
			),

			array(
				'id' => 3767,
				'HANDLE' => NULL,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => NULL,
				'Y' => NULL,
				'Z' => NULL,
				'A' => NULL,
				'B' => NULL,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:07',
				'updated_at' => '2016-02-01 11:32:07',
			),

			array(
				'id' => 3769,
				'HANDLE' => NULL,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => NULL,
				'Y' => NULL,
				'Z' => NULL,
				'A' => NULL,
				'B' => NULL,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:07',
				'updated_at' => '2016-02-01 11:32:07',
			),

			array(
				'id' => 3771,
				'HANDLE' => NULL,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => NULL,
				'Y' => NULL,
				'Z' => NULL,
				'A' => NULL,
				'B' => NULL,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:08',
				'updated_at' => '2016-02-01 11:32:08',
			),

			array(
				'id' => 3773,
				'HANDLE' => NULL,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => NULL,
				'Y' => NULL,
				'Z' => NULL,
				'A' => NULL,
				'B' => NULL,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:08',
				'updated_at' => '2016-02-01 11:32:08',
			),

			array(
				'id' => 3775,
				'HANDLE' => NULL,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => NULL,
				'Y' => NULL,
				'Z' => NULL,
				'A' => NULL,
				'B' => NULL,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:08',
				'updated_at' => '2016-02-01 11:32:08',
			),

			array(
				'id' => 3777,
				'HANDLE' => NULL,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => NULL,
				'Y' => NULL,
				'Z' => NULL,
				'A' => NULL,
				'B' => NULL,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:08',
				'updated_at' => '2016-02-01 11:32:08',
			),

			array(
				'id' => 3779,
				'HANDLE' => NULL,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => NULL,
				'Y' => NULL,
				'Z' => NULL,
				'A' => NULL,
				'B' => NULL,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:08',
				'updated_at' => '2016-02-01 11:32:08',
			),

			array(
				'id' => 3781,
				'HANDLE' => NULL,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => NULL,
				'Y' => NULL,
				'Z' => NULL,
				'A' => NULL,
				'B' => NULL,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:08',
				'updated_at' => '2016-02-01 11:32:08',
			),

			array(
				'id' => 3783,
				'HANDLE' => NULL,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => NULL,
				'Y' => NULL,
				'Z' => NULL,
				'A' => NULL,
				'B' => NULL,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:08',
				'updated_at' => '2016-02-01 11:32:08',
			),

			array(
				'id' => 3785,
				'HANDLE' => NULL,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => NULL,
				'Y' => NULL,
				'Z' => NULL,
				'A' => NULL,
				'B' => NULL,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:08',
				'updated_at' => '2016-02-01 11:32:08',
			),

			array(
				'id' => 3787,
				'HANDLE' => NULL,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => NULL,
				'Y' => NULL,
				'Z' => NULL,
				'A' => NULL,
				'B' => NULL,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:08',
				'updated_at' => '2016-02-01 11:32:08',
			),

			array(
				'id' => 3789,
				'HANDLE' => NULL,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => NULL,
				'Y' => NULL,
				'Z' => NULL,
				'A' => NULL,
				'B' => NULL,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:08',
				'updated_at' => '2016-02-01 11:32:08',
			),

			array(
				'id' => 3791,
				'HANDLE' => NULL,
				'FLG_REC' => 6,
				'NUM_COM' => 'MESA',
				'DES_COM' => NULL,
				'LOT_COM' => NULL,
				'DLO_COM' => NULL,
				'CLI_COM' => NULL,
				'IND_COM' => NULL,
				'DT1_COM' => '05/01/16',
				'DT2_COM' => NULL,
				'NUM_DIS' => 'D101',
				'DES_DIS' => NULL,
				'NOM_DIS' => NULL,
				'REV_DIS' => NULL,
				'DAT_DIS' => '05/01/16',
				'TRA_PEZ' => 'PINTADO',
				'SBA_PEZ' => NULL,
				'DES_SBA' => NULL,
				'TIP_PEZ' => NULL,
				'MAR_PEZ' => NULL,
				'MBU_PEZ' => NULL,
				'DES_PEZ' => 'A325 A325',
				'POS_PEZ' => NULL,
				'NOT_PEZ' => NULL,
				'ING_PEZ' => NULL,
				'MAX_LEN' => NULL,
				'QTA_PEZ' => 1,
				'QT1_PEZ' => NULL,
				'MCL_PEZ' => NULL,
				'COD_PEZ' => NULL,
				'COS_PEZ' => NULL,
				'NOM_PRO' => NULL,
				'LUN_PRO' => 0,
				'LAR_PRO' => 0,
				'SPE_PRO' => 0,
				'MAT_PRO' => 0502,
				'TIP_BUL' => 'A',
				'DIA_BUL' => 12.00,
				'LUN_BUL' => 44.40,
				'PRB_BUL' => 'Prf',
				'PUN_LIS' => 0.11,
				'SUN_LIS' => 0,
				'PRE_LIS' => NULL,
				'FLG_DWG' => 'D101',
				'obra_id' => 1,
				'lote_id' => NULL,
				'estagio_id' => NULL,
				'etapa_id' => 13,
				'subetapa_id' => NULL,
				'GROUP' => NULL,
				'CATE' => NULL,
				'importacao_id' => 15,
				'medicao_id' => NULL,
				'X' => NULL,
				'Y' => NULL,
				'Z' => NULL,
				'A' => NULL,
				'B' => NULL,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:09',
				'updated_at' => '2016-02-01 11:32:09',
			),

		));
		DB::table('importacoes')->insert(array(

			array(
				'id' => 15,
				'descricao' => 'Mesa',
				'cliente_id' => 1,
				'obra_id' => 1,
				'etapa_id' => 13,
				'subetapa_id' => 21,
				'dbf2d' => 'mesa-software.DBF',
				'ifc' => '1_ifc.obj',
				'fbx' => '1_fbx.obj',
				'ifc_orig' => 'mesa.ifc',
				'fbx_orig' => 'MESA.fbx',
				'erro_debug' => NULL,
				'importacaoNr' => 1,
				'observacoes' => 'Mesa',
				'sentido' => 1,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:32:04',
				'updated_at' => '2016-02-01 11:32:13',
			),

		));
		DB::table('locatarios')->insert(array(

			array(
				'id' => 1,
				'razao' => 'Metalfoort Indústria Metalúrgica',
				'fantasia' => 'Metalfoort',
				'tipo' => 0,
				'documento' => NULL,
				'inscricao' => NULL,
				'fone' => '51 3719 1086',
				'cidade' => 'Santa Cruz do Sul
	',
				'endereco' => 'Av. Felisberto B. de Moraes 80 - distrito Industrial',
				'cep' => '96835-645',
				'email' => 'projeto@metalfoort.com.br',
				'status' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),

		));
		DB::table('obra_user')->insert(array(

			array(
				'id' => 1,
				'obra_id' => 1,
				'user_id' => 4,
			),

			array(
				'id' => 3,
				'obra_id' => 1,
				'user_id' => 1,
			),

		));
		DB::table('obras')->insert(array(

			array(
				'id' => 1,
				'codigo' => 001,
				'nome' => 'TransVilmar',
				'descricao' => 'Descritivo da obra Teste',
				'cidade' => 'New York',
				'endereco' => '-',
				'cep' => '-',
				'cliente_id' => 1,
				'construtoraid' => NULL,
				'gerenciadoraid' => NULL,
				'calculistaid' => NULL,
				'detalhamentoid' => NULL,
				'montagemid' => NULL,
				'status' => 1,
				'user_id' => 1,
				'locatario_id' => 1,
				'created_at' => '2016-01-25 20:47:10',
				'updated_at' => '2016-01-25 20:47:10',
			),

		));
		DB::table('permission_dependencies')->insert(array(

			array(
				'id' => 1,
				'permission_id' => 2,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:46:54',
				'updated_at' => '2016-01-25 20:46:54',
			),

			array(
				'id' => 2,
				'permission_id' => 3,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:46:54',
				'updated_at' => '2016-01-25 20:46:54',
			),

			array(
				'id' => 3,
				'permission_id' => 3,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:46:55',
				'updated_at' => '2016-01-25 20:46:55',
			),

			array(
				'id' => 4,
				'permission_id' => 4,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:46:55',
				'updated_at' => '2016-01-25 20:46:55',
			),

			array(
				'id' => 5,
				'permission_id' => 4,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:46:55',
				'updated_at' => '2016-01-25 20:46:55',
			),

			array(
				'id' => 6,
				'permission_id' => 5,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:46:56',
				'updated_at' => '2016-01-25 20:46:56',
			),

			array(
				'id' => 7,
				'permission_id' => 5,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:46:56',
				'updated_at' => '2016-01-25 20:46:56',
			),

			array(
				'id' => 8,
				'permission_id' => 6,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:46:56',
				'updated_at' => '2016-01-25 20:46:56',
			),

			array(
				'id' => 9,
				'permission_id' => 6,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:46:57',
				'updated_at' => '2016-01-25 20:46:57',
			),

			array(
				'id' => 10,
				'permission_id' => 7,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:46:57',
				'updated_at' => '2016-01-25 20:46:57',
			),

			array(
				'id' => 11,
				'permission_id' => 7,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:46:57',
				'updated_at' => '2016-01-25 20:46:57',
			),

			array(
				'id' => 12,
				'permission_id' => 8,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:46:58',
				'updated_at' => '2016-01-25 20:46:58',
			),

			array(
				'id' => 13,
				'permission_id' => 8,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:46:58',
				'updated_at' => '2016-01-25 20:46:58',
			),

			array(
				'id' => 14,
				'permission_id' => 9,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:46:58',
				'updated_at' => '2016-01-25 20:46:58',
			),

			array(
				'id' => 15,
				'permission_id' => 9,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:46:59',
				'updated_at' => '2016-01-25 20:46:59',
			),

			array(
				'id' => 16,
				'permission_id' => 10,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:46:59',
				'updated_at' => '2016-01-25 20:46:59',
			),

			array(
				'id' => 17,
				'permission_id' => 10,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:46:59',
				'updated_at' => '2016-01-25 20:46:59',
			),

			array(
				'id' => 18,
				'permission_id' => 11,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:46:59',
				'updated_at' => '2016-01-25 20:46:59',
			),

			array(
				'id' => 19,
				'permission_id' => 11,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:47:00',
				'updated_at' => '2016-01-25 20:47:00',
			),

			array(
				'id' => 20,
				'permission_id' => 12,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:47:00',
				'updated_at' => '2016-01-25 20:47:00',
			),

			array(
				'id' => 21,
				'permission_id' => 12,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:47:00',
				'updated_at' => '2016-01-25 20:47:00',
			),

			array(
				'id' => 22,
				'permission_id' => 13,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:47:01',
				'updated_at' => '2016-01-25 20:47:01',
			),

			array(
				'id' => 23,
				'permission_id' => 13,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:47:01',
				'updated_at' => '2016-01-25 20:47:01',
			),

			array(
				'id' => 24,
				'permission_id' => 14,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:47:01',
				'updated_at' => '2016-01-25 20:47:01',
			),

			array(
				'id' => 25,
				'permission_id' => 14,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:47:02',
				'updated_at' => '2016-01-25 20:47:02',
			),

			array(
				'id' => 26,
				'permission_id' => 15,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:47:02',
				'updated_at' => '2016-01-25 20:47:02',
			),

			array(
				'id' => 27,
				'permission_id' => 15,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:47:02',
				'updated_at' => '2016-01-25 20:47:02',
			),

			array(
				'id' => 28,
				'permission_id' => 16,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:47:03',
				'updated_at' => '2016-01-25 20:47:03',
			),

			array(
				'id' => 29,
				'permission_id' => 16,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:47:03',
				'updated_at' => '2016-01-25 20:47:03',
			),

			array(
				'id' => 30,
				'permission_id' => 17,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:47:03',
				'updated_at' => '2016-01-25 20:47:03',
			),

			array(
				'id' => 31,
				'permission_id' => 17,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:47:04',
				'updated_at' => '2016-01-25 20:47:04',
			),

			array(
				'id' => 32,
				'permission_id' => 18,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:47:04',
				'updated_at' => '2016-01-25 20:47:04',
			),

			array(
				'id' => 33,
				'permission_id' => 18,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:47:04',
				'updated_at' => '2016-01-25 20:47:04',
			),

			array(
				'id' => 34,
				'permission_id' => 19,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:47:05',
				'updated_at' => '2016-01-25 20:47:05',
			),

			array(
				'id' => 35,
				'permission_id' => 19,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:47:05',
				'updated_at' => '2016-01-25 20:47:05',
			),

			array(
				'id' => 36,
				'permission_id' => 20,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:47:05',
				'updated_at' => '2016-01-25 20:47:05',
			),

			array(
				'id' => 37,
				'permission_id' => 20,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:47:06',
				'updated_at' => '2016-01-25 20:47:06',
			),

			array(
				'id' => 38,
				'permission_id' => 21,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:47:06',
				'updated_at' => '2016-01-25 20:47:06',
			),

			array(
				'id' => 39,
				'permission_id' => 21,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:47:06',
				'updated_at' => '2016-01-25 20:47:06',
			),

			array(
				'id' => 40,
				'permission_id' => 22,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:47:07',
				'updated_at' => '2016-01-25 20:47:07',
			),

			array(
				'id' => 41,
				'permission_id' => 22,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:47:08',
				'updated_at' => '2016-01-25 20:47:08',
			),

			array(
				'id' => 42,
				'permission_id' => 23,
				'dependency_id' => 1,
				'created_at' => '2016-01-25 20:47:08',
				'updated_at' => '2016-01-25 20:47:08',
			),

			array(
				'id' => 43,
				'permission_id' => 23,
				'dependency_id' => 2,
				'created_at' => '2016-01-25 20:47:08',
				'updated_at' => '2016-01-25 20:47:08',
			),

		));
		DB::table('permission_groups')->insert(array(

			array(
				'id' => 1,
				'parent_id' => NULL,
				'name' => 'Access',
				'sort' => 1,
				'created_at' => '2016-01-25 20:46:47',
				'updated_at' => '2016-01-25 20:46:47',
			),

			array(
				'id' => 2,
				'parent_id' => 1,
				'name' => 'User',
				'sort' => 1,
				'created_at' => '2016-01-25 20:46:47',
				'updated_at' => '2016-01-25 20:46:47',
			),

			array(
				'id' => 3,
				'parent_id' => 1,
				'name' => 'Role',
				'sort' => 2,
				'created_at' => '2016-01-25 20:46:47',
				'updated_at' => '2016-01-25 20:46:47',
			),

			array(
				'id' => 4,
				'parent_id' => 1,
				'name' => 'Permission',
				'sort' => 3,
				'created_at' => '2016-01-25 20:46:47',
				'updated_at' => '2016-01-25 20:46:47',
			),

		));
		DB::table('permissions')->insert(array(

			array(
				'id' => 1,
				'group_id' => 1,
				'name' => 'view-backend',
				'display_name' => 'View Backend',
				'system' => 1,
				'sort' => 1,
				'created_at' => '2016-01-25 20:46:49',
				'updated_at' => '2016-01-25 20:46:49',
			),

			array(
				'id' => 2,
				'group_id' => 1,
				'name' => 'view-access-management',
				'display_name' => 'View Access Management',
				'system' => 1,
				'sort' => 2,
				'created_at' => '2016-01-25 20:46:50',
				'updated_at' => '2016-01-25 20:46:50',
			),

			array(
				'id' => 3,
				'group_id' => 2,
				'name' => 'create-users',
				'display_name' => 'Create Users',
				'system' => 1,
				'sort' => 5,
				'created_at' => '2016-01-25 20:46:50',
				'updated_at' => '2016-01-25 20:46:50',
			),

			array(
				'id' => 4,
				'group_id' => 2,
				'name' => 'edit-users',
				'display_name' => 'Edit Users',
				'system' => 1,
				'sort' => 6,
				'created_at' => '2016-01-25 20:46:50',
				'updated_at' => '2016-01-25 20:46:50',
			),

			array(
				'id' => 5,
				'group_id' => 2,
				'name' => 'delete-users',
				'display_name' => 'Delete Users',
				'system' => 1,
				'sort' => 7,
				'created_at' => '2016-01-25 20:46:50',
				'updated_at' => '2016-01-25 20:46:50',
			),

			array(
				'id' => 6,
				'group_id' => 2,
				'name' => 'change-user-password',
				'display_name' => 'Change User Password',
				'system' => 1,
				'sort' => 8,
				'created_at' => '2016-01-25 20:46:50',
				'updated_at' => '2016-01-25 20:46:50',
			),

			array(
				'id' => 7,
				'group_id' => 2,
				'name' => 'deactivate-users',
				'display_name' => 'Deactivate Users',
				'system' => 1,
				'sort' => 9,
				'created_at' => '2016-01-25 20:46:50',
				'updated_at' => '2016-01-25 20:46:50',
			),

			array(
				'id' => 8,
				'group_id' => 2,
				'name' => 'reactivate-users',
				'display_name' => 'Re-Activate Users',
				'system' => 1,
				'sort' => 11,
				'created_at' => '2016-01-25 20:46:51',
				'updated_at' => '2016-01-25 20:46:51',
			),

			array(
				'id' => 9,
				'group_id' => 2,
				'name' => 'undelete-users',
				'display_name' => 'Restore Users',
				'system' => 1,
				'sort' => 13,
				'created_at' => '2016-01-25 20:46:51',
				'updated_at' => '2016-01-25 20:46:51',
			),

			array(
				'id' => 10,
				'group_id' => 2,
				'name' => 'permanently-delete-users',
				'display_name' => 'Permanently Delete Users',
				'system' => 1,
				'sort' => 14,
				'created_at' => '2016-01-25 20:46:51',
				'updated_at' => '2016-01-25 20:46:51',
			),

			array(
				'id' => 11,
				'group_id' => 2,
				'name' => 'resend-user-confirmation-email',
				'display_name' => 'Resend Confirmation E-mail',
				'system' => 1,
				'sort' => 15,
				'created_at' => '2016-01-25 20:46:51',
				'updated_at' => '2016-01-25 20:46:51',
			),

			array(
				'id' => 12,
				'group_id' => 3,
				'name' => 'create-roles',
				'display_name' => 'Create Roles',
				'system' => 1,
				'sort' => 2,
				'created_at' => '2016-01-25 20:46:51',
				'updated_at' => '2016-01-25 20:46:51',
			),

			array(
				'id' => 13,
				'group_id' => 3,
				'name' => 'edit-roles',
				'display_name' => 'Edit Roles',
				'system' => 1,
				'sort' => 3,
				'created_at' => '2016-01-25 20:46:51',
				'updated_at' => '2016-01-25 20:46:51',
			),

			array(
				'id' => 14,
				'group_id' => 3,
				'name' => 'delete-roles',
				'display_name' => 'Delete Roles',
				'system' => 1,
				'sort' => 4,
				'created_at' => '2016-01-25 20:46:52',
				'updated_at' => '2016-01-25 20:46:52',
			),

			array(
				'id' => 15,
				'group_id' => 4,
				'name' => 'create-permission-groups',
				'display_name' => 'Create Permission Groups',
				'system' => 1,
				'sort' => 1,
				'created_at' => '2016-01-25 20:46:52',
				'updated_at' => '2016-01-25 20:46:52',
			),

			array(
				'id' => 16,
				'group_id' => 4,
				'name' => 'edit-permission-groups',
				'display_name' => 'Edit Permission Groups',
				'system' => 1,
				'sort' => 2,
				'created_at' => '2016-01-25 20:46:52',
				'updated_at' => '2016-01-25 20:46:52',
			),

			array(
				'id' => 17,
				'group_id' => 4,
				'name' => 'delete-permission-groups',
				'display_name' => 'Delete Permission Groups',
				'system' => 1,
				'sort' => 3,
				'created_at' => '2016-01-25 20:46:52',
				'updated_at' => '2016-01-25 20:46:52',
			),

			array(
				'id' => 18,
				'group_id' => 4,
				'name' => 'sort-permission-groups',
				'display_name' => 'Sort Permission Groups',
				'system' => 1,
				'sort' => 4,
				'created_at' => '2016-01-25 20:46:52',
				'updated_at' => '2016-01-25 20:46:52',
			),

			array(
				'id' => 19,
				'group_id' => 4,
				'name' => 'create-permissions',
				'display_name' => 'Create Permissions',
				'system' => 1,
				'sort' => 5,
				'created_at' => '2016-01-25 20:46:53',
				'updated_at' => '2016-01-25 20:46:53',
			),

			array(
				'id' => 20,
				'group_id' => 4,
				'name' => 'edit-permissions',
				'display_name' => 'Edit Permissions',
				'system' => 1,
				'sort' => 6,
				'created_at' => '2016-01-25 20:46:53',
				'updated_at' => '2016-01-25 20:46:53',
			),

			array(
				'id' => 21,
				'group_id' => 4,
				'name' => 'delete-permissions',
				'display_name' => 'Delete Permissions',
				'system' => 1,
				'sort' => 7,
				'created_at' => '2016-01-25 20:46:53',
				'updated_at' => '2016-01-25 20:46:53',
			),

		));
		DB::table('roles')->insert(array(

			array(
				'id' => 1,
				'name' => 'Administrator',
				'all' => 1,
				'sort' => 1,
				'created_at' => '2016-01-25 20:46:44',
				'updated_at' => '2016-01-25 20:46:44',
			),

			array(
				'id' => 2,
				'name' => 'User',
				'all' => 0,
				'sort' => 2,
				'created_at' => '2016-01-25 20:46:44',
				'updated_at' => '2016-01-25 20:46:44',
			),

		));
		DB::table('subetapas')->insert(array(

			array(
				'id' => 19,
				'cod' => 'Estrutura',
				'peso' => 10000,
				'tiposubetapa_id' => 1,
				'observacao' => 'Estrutura',
				'etapa_id' => 11,
				'user_id' => 4,
				'locatario_id' => 1,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),

			array(
				'id' => 21,
				'cod' => 'MESA-A',
				'peso' => 500,
				'tiposubetapa_id' => 1,
				'observacao' => 'Mesa',
				'etapa_id' => 13,
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 11:29:32',
				'updated_at' => '2016-02-01 11:29:32',
			),

		));
		DB::table('tiposcontatos')->insert(array(

			array(
				'id' => 1,
				'descricao' => 'Gerenciadora',
				'user_id' => 1,
				'locatario_id' => 1,
				'created_at' => '2016-01-30 03:21:51',
				'updated_at' => '2016-01-30 03:21:51',
			),

			array(
				'id' => 3,
				'descricao' => 'Contador',
				'user_id' => 1,
				'locatario_id' => 1,
				'created_at' => '2016-01-30 03:26:23',
				'updated_at' => '2016-01-30 03:26:23',
			),

			array(
				'id' => 5,
				'descricao' => 'Engenheiro',
				'user_id' => 1,
				'locatario_id' => 1,
				'created_at' => '2016-01-30 03:31:25',
				'updated_at' => '2016-01-30 03:31:25',
			),

		));
		DB::table('tiposestagios')->insert(array(

			array(
				'id' => 2,
				'decricao' => 'fabricacao
',
				'user_id' => 2,
				'locatario_id' => 1,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),

		));
		DB::table('tipossubetapas')->insert(array(

			array(
				'id' => 1,
				'descricao' => 'Estrutura',
				'user_id' => 1,
				'locatario_id' => 1,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),

			array(
				'id' => 3,
				'descricao' => 'Telhas',
				'user_id' => 1,
				'locatario_id' => 1,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '0000-00-00 00:00:00',
			),

		));
		DB::table('users')->insert(array(

			array(
				'id' => 1,
				'name' => 'Admin',
				'email' => 'admin@admin.com',
				'password' => 1234,
				'status' => 1,
				'confirmation_code' => 'f3af2693b1b568e536c8517ec54e00eb',
				'confirmed' => 1,
				'remember_token' => '2UqEFAgZtzVp6Q0xhvKKsB9TF4jeKoLBH55KH69yc4YM8tKwQajw3GDNlzyc',
				'locatario_id' => 1,
				'created_at' => '2016-01-25 20:46:43',
				'updated_at' => '2016-01-31 13:53:10',
				'deleted_at' => NULL,
			),

			array(
				'id' => 2,
				'name' => 'User',
				'email' => 'user@user.com',
				'password' => '$2y$10$DcVzmaZlX2P/IVimRUl/TubLU4PxA9iK18p0DuiPAWe1PlCvsNrnS',
				'status' => 1,
				'confirmation_code' => 'b468db2db87148ac54f5f77724e6a379',
				'confirmed' => 1,
				'remember_token' => 'bWw23fcfKQ9OCHJOGXsGp0XhbcXwa9BA0FvgyjGq4rEWbjJi9r3nNnIuCi4h',
				'locatario_id' => 1,
				'created_at' => '2016-01-25 20:46:43',
				'updated_at' => '2016-02-01 15:01:22',
				'deleted_at' => NULL,
			),

			array(
				'id' => 3,
				'name' => 'Àdmin2',
				'email' => 'admin2@admin.com',
				'password' => '$10$6SjeBxA6lyKyTgtOwvrPKe05A7ERW3CmbNeDW9S8hj9whSKMLEbe6',
				'status' => 1,
				'confirmation_code' => 'b468db2db87148ac54f5f77724e6a379',
				'confirmed' => 1,
				'remember_token' => NULL,
				'locatario_id' => 1,
				'created_at' => '2016-01-31 11:52:37',
				'updated_at' => '0000-00-00 00:00:00',
				'deleted_at' => NULL,
			),

			array(
				'id' => 4,
				'name' => 'Metalfoort',
				'email' => 'projeto@metalfoort.com.br',
				'password' => 123456,
				'status' => 1,
				'confirmation_code' => NULL,
				'confirmed' => 1,
				'remember_token' => NULL,
				'locatario_id' => 1,
				'created_at' => '2016-02-01 08:20:10',
				'updated_at' => '0000-00-00 00:00:00',
				'deleted_at' => NULL,
			),

			array(
				'id' => 5,
				'name' => 'Luciano',
				'email' => 'tonetlds@gmail.com',
				'password' => '$2y$10$ExZ9T4expXhfrsLF7E92wONSpB06YWm353W9aKpuQ7U30ydeKSeMC',
				'status' => 1,
				'confirmation_code' => NULL,
				'confirmed' => 1,
				'remember_token' => 'OOZoxhjqYpd81vf6oibgt1Qhd30RyHvVTf4R5doOX81rd5CZr64azNLgTibV',
				'locatario_id' => 1,
				'created_at' => '2016-02-01 09:48:43',
				'updated_at' => '2016-02-01 15:02:10',
				'deleted_at' => NULL,
			),

		));

		if (env('DB_CONNECTION') == 'mysql') {
			DB::statement('SET FOREIGN_KEY_CHECKS=1;');
		}
	}
}